name: Lint

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Lint Client
        run: |
          cd client
          npm i
          npm run lint
          npm run build

      - name: Lint Server
        run: |
          cd server
          npm i
          npm run lint

      - name: Create Client Environment File
        run: |
          cd client
          echo "NODE_ENV=${{secrets.CLIENT_NODE_ENV}}" > .env
          echo "VITE_REACT_SERVER_URL=${{secrets.CLIENT_VITE_REACT_SERVER_URL}}" >> .env
          cd ..

      - name: Create Server Environment File
        run: |
          cd server
          echo "NODE_ENV=${{secrets.SERVER_NODE_ENV}}" > .env
          echo "JWT_SECRET=${{secrets.SERVER_JWT_SECRET}}" >> .env
          echo "SESSION_SECRET=${{secrets.SERVER_SESSION_SECRET}}" >> .env
          echo "MONGO_URI=${{secrets.SERVER_MONGO_URI}}" >> .env
          echo "TWITTER_API_KEY=${{secrets.SERVER_TWITTER_API_KEY}}" >> .env
          echo "TWITTER_API_SECRET=${{secrets.SERVER_TWITTER_API_SECRET}}" >> .env
          echo "TWITTER_ACCESS_TOKEN=${{secrets.SERVER_TWITTER_ACCESS_TOKEN}}" >> .env
          echo "TWITTER_ACCESS_TOKEN_SECRET=${{secrets.SERVER_TWITTER_ACCESS_TOKEN_SECRET}}" >> .env
          cd ..

      - name: Upload Frontend
        id: push_directory_frontend
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: client/build
          destination-github-username: "freight-capstone"
          destination-repository-name: "hr2"
          user-email: pedjovensindol.edu@gmail.com
          commit-message: Production
          target-branch: hr2-frontend

      - name: Build Backend
        run: |
          cd server
          npm i
          npm run build
          npm run build:obfuscate
          cd ..
          rm -rf server/src
          rm -rf server/dist/obsfucate.js

      - name: Upload Backend
        id: push_directory_backend
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: server
          destination-github-username: "freight-capstone"
          destination-repository-name: "hr2"
          user-email: pedjovensindol.edu@gmail.com
          commit-message: Production
          target-branch: hr2-backend
