name: Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-client:
    runs-on: "ubuntu-latest"
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Lint Client
        run: |
          cd client
          npm i
          npm run lint

      - name: Setup Environment Variables
        run: |
          cd client
          echo "VITE_NODE_ENV=production" > .env
          echo "VITE_REACT_SERVER_URL=https://hr2-backend.axleshift.com" >> .env

      - name: Build Client
        run: |
          cd client
          npm run build

      - name: Push to client branch
        id: push_client
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: client/build
          destination-github-username: freight-capstone
          destination-repository-name: hr2
          target-branch: hr2-frontend
          user-email: "pedjovensindol.edu@gmail.com"
          commit-message: "Build client"

  build-server:
    runs-on: "ubuntu-latest"
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Lint Server
        run: |
          cd server
          npm i
          npm run lint

      - name: Build Server
        run: |
          cd server
          npm run build
          npm run build:obfuscate
          rm -rf src dist/obfuscate.js eslint.config.mjs .prettierrc tsconfig.json

      - name: Push to server branch
        id: push_server
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: server
          destination-github-username: freight-capstone
          destination-repository-name: hr2
          target-branch: hr2-backend
          user-email: "pedjovensindol.edu@gmail.com"
          commit-message: "Build server"
