name: Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-client:
    runs-on: "ubuntu-latest"
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Lint Client
        run: |
          cd client
          npm i
          npm run lint:fix

      - name: Setup Environment Variables
        run: |
          cd client
          echo "VITE_NODE_ENV=${{ secrets.CLIENT_NODE_ENV}}" > .env
          echo "VITE_REACT_SERVER_URL=${{ secrets.CLIENT_VITE_REACT_SERVER_URL}}" >> .env
          echo "VITE_REACT_GOOGLE_RECAPTCHA_SITE_KEY=${{ secrets.CLIENT_GOOGLE_RECAPTCHA_SITE_KEY}}" >> .env
          echo "VITE_REACT_GOOGLE_RECAPTCHA_SECRET_KEY=${{ secrets.CLIENT_GOOGLE_RECAPTCHA_SECRET_KEY}}" >> .env

      - name: Build Client
        run: |
          cd client
          npm run build

      - name: Push to client branch
        id: push_client
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: client/build
          destination-github-username: ${{secrets.DESTINATION_GITHUB_USERNAME}}
          destination-repository-name: ${{secrets.DESTINATION_REPOSITORY_NAME}}
          target-branch: ${{secrets.CLIENT_TARGET_BRANCH}}
          user-email: "pedjovensindol.edu@gmail.com"
          commit-message: "Build client"

  build-server:
    runs-on: "ubuntu-latest"
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Lint Server
        run: |
          cd server
          npm i
          npm run lint:fix

      - name: Setup Environment Variables
        run: |
            cd server
            echo "NODE_ENV=${{ secrets.SERVER_NODE_ENV}}" > .env
            echo "SERVER_PORT=${{ secrets.SERVER_PORT}}" >> .env
            echo "SERVER_HOST=${{ secrets.SERVER_HOST}}" >> .env
            echo "SERVER_TRUST_PROXY=${{ secrets.SERVER_TRUST_PROXY}}" >> .env
            echo "SERVER_CSRF=${{ secrets.SERVER_CSRF}}" >> .env
            echo "CORS_ORIGINS=${{ secrets.SERVER_CORS_ORIGINS}}" >> .env
            echo "JWT_SECRET=${{ secrets.SERVER_JWT_SECRET}}" >> .env
            echo "JWT_EXPIRES_IN=${{ secrets.SERVER_JWT_EXPIRES_IN}}" >> .env
            echo "SESSION_SECRET=${{ secrets.SERVER_SESSION_SECRET}}" >> .env
            echo "SESSION_EXPIRES_IN=${{ secrets.SERVER_SESSION_EXPIRES_IN}}" >> .env
            echo "SESSION_EXCEPTIONS=${{ secrets.SERVER_SESSION_EXCEPTIONS}}" >> .env
            echo "GOOGLE_FORMS_KEY=${{ secrets.SERVER_GOOGLE_FORMS_KEY}}" >> .env
            echo "MONGODB_USERNAME=${{ secrets.SERVER_MONGODB_USERNAME}}" >> .env
            echo "MONGODB_PASSWORD=${{ secrets.SERVER_MONGODB_PASSWORD}}" >> .env
            echo "MONGODB_CLUSTER=${{ secrets.SERVER_MONGODB_CLUSTER}}" >> .env
            echo "MONGODB_OPTIONS=${{ secrets.SERVER_MONGODB_OPTIONS}}" >> .env
            echo "API_MASTER_KEY=${{ secrets.SERVER_API_MASTER_KEY}}" >> .env
            echo "TWITTER_API_KEY=${{ secrets.SERVER_TWITTER_API_KEY}}" >> .env
            echo "TWITTER_API_SECRET=${{ secrets.SERVER_TWITTER_API_SECRET}}" >> .env
            echo "TWITTER_ACCESS_TOKEN=${{ secrets.SERVER_TWITTER_ACCESS_TOKEN}}" >> .env
            echo "TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.SERVER_TWITTER_ACCESS_TOKEN_SECRET}}" >> .env
            echo "PROMETHEUS_METRICS_PREFIX=${{ secrets.SERVER_PROMETHEUS_METRICS_PREFIX}}" >> .env

      - name: Build Server
        run: |
          cd server
          npm run build
          # npm run build:obfuscate
          rm -rf src dist/obfuscate.js eslint.config.mjs .prettierrc tsconfig.json

      - name: Push to server branch
        id: push_server
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: server
          destination-github-username: ${{secrets.DESTINATION_GITHUB_USERNAME}}
          destination-repository-name: ${{secrets.DESTINATION_REPOSITORY_NAME}}
          target-branch: ${{secrets.SERVER_TARGET_BRANCH}}
          user-email: "pedjovensindol.edu@gmail.com"
          commit-message: "Build server"
