name: Labeler
on: 
  pull_request_target:

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        repository: "${{secrets.DESTINATION_GITHUB_USERNAME}}/${{secrets.DESTINATION_REPOSITORY_NAME}}"
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.API_TOKEN_GITHUB }}"
        configuration-path: '.github/labeler.yml'